### ISSUE TITLE
Abacus export with item based tax not successfull

### ISSUE THREAD

**Issue by cdiethelm** [phamos-eu/Swiss-Accounting-Integration#19]
Hello, 

Here is our situation: 
There are completely deductable positions on invoices which have a separate tax code. The taxrate for these items is 100% included in the item price. 

Example: 
Item 1 - 14.90 CHF
Total invoice cost - 14.90 CHF

This is an example file from our old ERP System: 

<Transaction>

    <Entry mode='SAVE'>
      <CollectiveInformation mode='SAVE'>
        <EntryLevel>A</EntryLevel>
        <EntryType>S</EntryType>
        <Type>Normal</Type>
        <DebitCredit>D</DebitCredit>
        <Client>2418</Client>
        <Division>0</Division>
        <KeyCurrency>CHF</KeyCurrency>
        <EntryDate>2021-12-03</EntryDate>
        <ValueDate>2021-12-03</ValueDate>
        <AmountData mode='SAVE'>
          <Currency>CHF</Currency>
          <Amount>1904.50</Amount>
        </AmountData>
        <KeyAmount>1904.50</KeyAmount>
        <Account>470000</Account>
        <TaxAccount>470000</TaxAccount>
        <IntercompanyId>0</IntercompanyId>
        <IntercompanyCode/>
        <BookingLevel1>9999</BookingLevel1>
        <BookingLevel2>0</BookingLevel2>
        <BookingLevel3>0</BookingLevel3>
        <Text1>(Supplier)</Text1>
        <Text2>(Invoice No)</Text2>
        <DocumentNumber>26253</DocumentNumber>
        <SingleCount>0</SingleCount>
        <BookingSource>E</BookingSource>
      </CollectiveInformation>
      <SingleInformation mode='SAVE'>
        <Type>Normal</Type>
        <DebitCredit>D</DebitCredit>
        <EntryDate>2021-12-03</EntryDate>
        <ValueDate>2021-12-03</ValueDate>
        <AmountData mode='SAVE'>
          <Currency>CHF</Currency>
          <Amount>1904.50</Amount>
        </AmountData>
        <KeyAmount>1904.50</KeyAmount>
        <Account>200000</Account>
        <TaxAccount>0</TaxAccount>
        <IntercompanyId>0</IntercompanyId>
        <IntercompanyCode/>
        <BookingLevel1>0</BookingLevel1>
        <BookingLevel2>0</BookingLevel2>
        <BookingLevel3>0</BookingLevel3>
        <Text1>(Supplier)</Text1>
        <Text2>(Invoice No)</Text2>
        <DocumentNumber>26253</DocumentNumber>
        <SelectionCode/>
        <TaxData mode="SAVE">
          <TaxIncluded>I</TaxIncluded>
          <TaxType>1</TaxType>
          <UseCode>0</UseCode>
          <AmountData mode="SAVE">
            <Currency>CHF</Currency>
            <Amount>0</Amount>
          </AmountData>
          <KeyAmount>-1904.50</KeyAmount>
          <TaxRate>100.00</TaxRate>
          <TaxCoefficient>100</TaxCoefficient>
          <Country>CH</Country>
          <TaxCode>115</TaxCode>
          <Number/>
          <FlatRate>0</FlatRate>
        </TaxData>
        <NoteData mode='SAVE'>
          <Text>(Transaction Number)</Text>
        </NoteData>
      </SingleInformation>
    </Entry>
  </Transaction>

This is an example from ERPNext with the Swiss Accounting integration: 

```
<?xml version="1.0" encoding="UTF-8"?>
<!-- This export has data from 2022-02-01 to 2022-03-31 and has 6 Sales Invoices, 1 Purchase Invoices and 0 Payment Entry -->
<AbaConnectContainer>
    <TaskCount>0</TaskCount>
    <Task>
        <Parameter>
            <Application>FIBU</Application>
            <Id>XML Buchungen</Id>
            <MapId>AbaDefault</MapId>
            <Version>2015.00</Version>
        </Parameter>
        <Transaction id="1">
            <Entry mode="SAVE">
                <CollectiveInformation mode="SAVE">
                    <EntryLevel>A</EntryLevel>
                    <EntryType>S</EntryType>
                    <Type>Normal</Type>
                    <DebitCredit>C</DebitCredit>
					<Client></Client>
                    <Division>0</Division>
                    <KeyCurrency>CHF</KeyCurrency>
                    <EntryDate>2022-03-21</EntryDate>ö
                    <ValueDate>2022-03-21</ValueDate>
                    <AmountData mode="SAVE">
                        <Currency>CHF</Currency>
                        <Amount>14.40</Amount>
                    </AmountData>
                    <KeyAmount>14.40</KeyAmount>
                    <Account></Account>
                    <IntercompanyId>0</IntercompanyId>
                    <IntercompanyCode></IntercompanyCode>
                    <Text1>ACC-PINV-2022-00002-5</Text1>
                    <DocumentNumber>2022000025</DocumentNumber>
                    <SingleCount>1</SingleCount>
                </CollectiveInformation>
                <SingleInformation mode="SAVE">
                    <Type>Normal</Type>
                    <DebitCredit>C</DebitCredit>
                    <EntryDate>2022-03-21</EntryDate>
                    <ValueDate></ValueDate>
                    <AmountData mode="SAVE">
                        <Currency>CHF</Currency>
                        <Amount>14.40</Amount>
                    </AmountData>
                    <KeyAmount>14.4</KeyAmount>
                    <Account></Account>
                    <TaxCode>115</TaxCode>
		    <IntercompanyId>0</IntercompanyId>
                    <IntercompanyCode></IntercompanyCode>
                    <Text1>ACC-PINV-2022-00002-5</Text1>
                    <DocumentNumber>2022000025</DocumentNumber>
                    <SelectionCode></SelectionCode>
                </SingleInformation>
            </Entry>
        </Transaction>
    </Task>
</AbaConnectContainer>
```

Notice that the tax information is not stored in TaxData. This returns the following error in Abacus:

```
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type="text/xsl" href="Response.xsl"?>
<AbaResponse>
  <ResponseStateSetting>Warning</ResponseStateSetting>
  <ResponseState>Error</ResponseState>
  <Information>
    <ActionType>IMPORT</ActionType>
    <TimeStamp>21.03.2022 11:56:53.614</TimeStamp>
    <FileName>path</FileName>
  </Information>
  <Statistic mode='Task'>
    <Information>0</Information>
    <Warning>0</Warning>
    <Error>1</Error>
  </Statistic>
  <Messages>
    <Message state='Error' code='3028'>Element TaxCode in SingleInformation ist von unbekanntem Typ.</Message>
  </Messages>
  <Task name='XML Buchungen (1)'>
    <ResponseState>Error</ResponseState>
    <Information>
      <Definition>XML Buchungen</Definition>
      <Mapping>AbaDefault</Mapping>
      <Application>fibu</Application>
      <Version>2015.0</Version>
      <Mandant>2418</Mandant>
    </Information>
    <Statistic mode='Transaction'>
      <TransactionCount>1</TransactionCount>
      <Information>0</Information>
      <Warning>0</Warning>
      <Error>1</Error>
    </Statistic>
    <Transaction name='0' id='1'>
      <ResponseState>Error</ResponseState>
      <Statistic mode='Element'>
        <Information>0</Information>
        <Warning>0</Warning>
        <Error>1</Error>
      </Statistic>
      <Element name='Entry'>
        <ResponseState>Error</ResponseState>
        <Element name='SingleInformation'>
          <ResponseState>Error</ResponseState>
          <Messages>
            <Message state='Error' code='3028'>Element TaxCode in SingleInformation ist von unbekanntem Typ.</Message>
          </Messages>
          <Data name='Type'>
            <ResponseState>Information</ResponseState>
            <Value>Normal</Value>
          </Data>
          <Data name='DebitCredit'>
            <ResponseState>Information</ResponseState>
            <Value>C</Value>
          </Data>
          <Data name='EntryDate'>
            <ResponseState>Information</ResponseState>
            <Value>2022-03-21</Value>
          </Data>
          <Data name='ValueDate'>
            <ResponseState>Information</ResponseState>
            <Value/>
          </Data>
          <Data name='KeyAmount'>
            <ResponseState>Information</ResponseState>
            <Value>14.4</Value>
          </Data>
          <Data name='Account'>
            <ResponseState>Information</ResponseState>
            <Value>0</Value>
          </Data>
          <Data name='IntercompanyId'>
            <ResponseState>Information</ResponseState>
            <Value>0</Value>
          </Data>
          <Data name='IntercompanyCode'>
            <ResponseState>Information</ResponseState>
            <Value/>
          </Data>
          <Data name='Text1'>
            <ResponseState>Information</ResponseState>
            <Value>ACC-PINV-2022-00002-5</Value>
          </Data>
          <Data name='DocumentNumber'>
            <ResponseState>Information</ResponseState>
            <Value>2022000025</Value>
          </Data>
          <Data name='SelectionCode'>
            <ResponseState>Information</ResponseState>
            <Value/>
          </Data>
          <Data name='TaxCode'>
            <ResponseState>Information</ResponseState>
            <Value>115</Value>
          </Data>
        </Element>
      </Element>
    </Transaction>
  </Task>
</AbaResponse>
```

**Comment by wojosc** [comment]
@estackhub please assess this issue.

**Comment by estackhub** [comment]
@wojosc invoices.against_singles always returns empty [ ].
Looking into the return structure and length of "invoices.against_singles"

**Comment by wojosc** [comment]
Thank you @estackhub . There is something else we need to look at here first I think.

@cdiethelm you would like to reflect "EUSt" right? ERPNext is set to cover this in the Taxes and Charges Table rather than doing this via an item. Is this known to you?

**Comment by cdiethelm** [comment]
@wojosc Yes, that is known to me. Our issue is that we cannot have different tax codes in the invoice. 
Example: 
For the "EUSt", we need tax code 115, for regular taxes 140. 
There should be a field in the table "purchase taxes and charges" to set an individual account.
Right now, this is handled via "Purchase taxes and charges template". We cannot choose multiple templates.

**Comment by wojosc** [comment]
Hi @cdiethelm from a user persepective...would it be sufficient to have a field "Tax Code" inside the Taxes and Charges Table?
![grafik](https://user-images.githubusercontent.com/22279621/160552944-f95c71d4-c296-423b-ac04-2ba58de5a2b0.png)

**Comment by cdiethelm** [comment]
Hello @wojosc, Yes, that would fit our use case. Since the user already has to put in the tax value, he could also put in the tax code.

**Comment by wojosc** [comment]
@cdiethelm I have added the field on the staging platform. Please have a look.

It won't be available in the Abacus Export yet but you'll be able to check if you can pull all the information over a custom report I have created:
![grafik](https://user-images.githubusercontent.com/22279621/160557130-d8481e5f-93de-4a59-8097-f3bf936aa949.png)

**Comment by cdiethelm** [comment]
Hello @wojosc , account 115 is present in the view, so that is correct. 

![image](https://user-images.githubusercontent.com/46853231/160755499-39952f73-918b-434a-8674-e10c44f5de2f.png)

The other content would have tax code 131 from the template.

**Comment by cdiethelm** [comment]
@wojosc Please note, that we need that for Purchase Invoice, not Sales invoice.

**Comment by cdiethelm** [comment]
@wojosc Are there any news on this subject? Anything I could help?

**Comment by wojosc** [comment]
@cdiethelm as just discussed:

The field for the Swiss Tax Code on the UI will be called "Steuerziffer CH" and carry the technical fieldname steuerziffer_ch to avoid conflict with other tax related fields coming from frappe or third party apps.

We have quickly discussed and tested the use of Accounting Dimensions to quickly employ the field on all accounting relevant transactions documents which are, but not limit to

- Sales Invoice
- Sales Invoice Item
- Purchase Invoice
- Purchase Invoice Item
- Payment
- Delivery Note
- ...

With implementing the field via the UI the requirement to be able to input and document the "Steuerziffer (Tax Code)" is fulfilled.

Further we will need to map (and remap due to the field name change) the field "steuerziffer_ch" to the Abacus Field <TaxCode> as seen in the XML export.

The mapping needs to be done on

Item Level and Sales Taxes and Charges Level. Both on Sales Invoice and Purchase Invoice. Although the Purchase Invoice has the higher priority

Tasks

- [ ] Change Fieldnames on UI
- [ ] Change mapping in the code for Item level
- [ ] Change mapping in the code for Charges and Taxes level

@cdiethelm please quickly let me know if there are further steps to take befor we start with this. Thank you.

**Comment by wojosc** [comment]
@estackhub fyi

**Comment by cdiethelm** [comment]
@wojosc I think its all clear now. Looks good to me. 👍

**Comment by cdiethelm** [comment]
@wojosc We have an error with the export. Should that be an optional value? 


### App Versions
```
{
	"erpnext": "14.0.0-dev",
	"frappe": "14.0.0-dev",
	"swiss_accounting_integration": "0.0.6",
	"wiki": "0.0.1"
}
```
### Route
```
Form/Abacus Export/jan
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.submit()
  File "apps/frappe/frappe/model/document.py", line 997, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 986, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 295, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 346, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1065, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 920, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1242, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1226, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/swiss_accounting_integration/swiss_accounting_integration/__init__.py", line 167, in attach_xml
    attach(doc.company, doc.start_date, doc.end_date, doc.doctype, doc.name)
  File "apps/swiss_accounting_integration/swiss_accounting_integration/__init__.py", line 159, in attach
    gl_xml = gl(company, start_date, end_date)
  File "apps/swiss_accounting_integration/swiss_accounting_integration/__init__.py", line 92, in gl
    inv_amt(item, item.expense_account, inv.currency,
  File "apps/swiss_accounting_integration/swiss_accounting_integration/utils.py", line 174, in amount
    'tax_code': item.tax_code or "312",
AttributeError: 'PurchaseInvoiceItem' object has no attribute 'tax_code'

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1493, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.submit()
  File "apps/frappe/frappe/model/document.py", line 997, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 986, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 295, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 346, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1065, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 920, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1242, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1226, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/swiss_accounting_integration/swiss_accounting_integration/__init__.py", line 167, in attach_xml
    attach(doc.company, doc.start_date, doc.end_date, doc.doctype, doc.name)
  File "apps/swiss_accounting_integration/swiss_accounting_integration/__init__.py", line 159, in attach
    gl_xml = gl(company, start_date, end_date)
  File "apps/swiss_accounting_integration/swiss_accounting_integration/__init__.py", line 92, in gl
    inv_amt(item, item.expense_account, inv.currency,
  File "apps/swiss_accounting_integration/swiss_accounting_integration/utils.py", line 174, in amount
    'tax_code': item.tax_code or "312",
AttributeError: 'PurchaseInvoiceItem' object has no attribute 'tax_code'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{,\"doctype\":\"Abacus Export\"}",
		"action": "Submit"
	},
	"btn": {
		"jQuery3600018627082573897671": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 884,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exception": "AttributeError: 'PurchaseInvoiceItem' object has no attribute 'tax_code'"
}
```

**Comment by wojosc** [comment]
@cdiethelm the change was only implemented for the Sales Invoice for the moment. We should test that first.

For now, try adding a field tax_code to your Purchase Invoice Item to solve your error. If you need help, please call. Thank you.
